name = "email-responder"
main = "src/index.ts"
compatibility_date = "2023-03-29"

[vars]
GMAIL_FORWARD_TO = "alengeoalex@gmail.com"
GMAIL_REPLY_EMAIL = "no-reply@alenalex.me"
GMAIL_REPLY_NAME = "Alen Alex"
FAILOVER_CONTACT = "https://alenalex.me"