name = "email-responder"
main = "src/index.ts"
compatibility_date = "2023-03-29"

[vars]
GMAIL_FORWARD_TO = "xxxxxxx@gmail.com"
GMAIL_REPLY_EMAIL = "no-reply@yourdomain.com"
GMAIL_REPLY_NAME = "Your Name"
FAILOVER_CONTACT = "xxxxxxx@gmail.com or xxxxxxx.com"